# Generated by Django 3.2.5 on 2021-07-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customerform'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerform',
            name='subject',
            field=models.TextField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customerform',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
