# Generated by Django 3.2.5 on 2021-08-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210713_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='contact_no',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
